In [3]:
from __future__ import print_function
import torch as t
import numpy as np
#指定形状
x = t.Tensor(5, 3)
x

tensor([[1.5469e+03, 4.5724e-41, 1.5469e+03],
        [4.5724e-41, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 9.0911e+26, 1.6707e+22],
        [9.6651e-39, 1.0561e-38, 1.6615e+35]])

In [4]:
#使用[0,1]均匀分布随机初始化二维数组
x = t.rand(5, 3)
y = t.rand(5, 3)
x

tensor([[6.4485e-02, 3.6213e-01, 9.0230e-02],
        [4.0126e-04, 1.2015e-01, 6.6389e-01],
        [9.6473e-01, 2.4135e-01, 4.2606e-02],
        [7.4289e-01, 6.0757e-01, 4.9955e-01],
        [8.0281e-02, 2.1153e-01, 2.8384e-01]])

In [5]:
#查看x形状
print(x.size())

#查看列个数,方法1
#方法1
x.size()[0]

#方法2
x.size(0)


torch.Size([5, 3])


5

In [6]:
x + y         #1
t.add(x, y)   #2
result = t.Tensor(5, 3)    #3 
t.add(x, y, out=result)
result

tensor([[0.7659, 0.3630, 0.7677],
        [0.0308, 0.1960, 0.8200],
        [1.3477, 0.7604, 0.9311],
        [1.2765, 0.7849, 0.6634],
        [0.7062, 0.7491, 0.3598]])

In [7]:
print ('最初的y')
print (y)

print('第一种加法结果')
y.add(x)  #普通加法，不改变y的值
print (y)

print('第二种加法结果')
y.add_(x)  #inplace 加法，改变y的值
print (y)

最初的y
tensor([[0.7014, 0.0009, 0.6775],
        [0.0304, 0.0759, 0.1562],
        [0.3829, 0.5190, 0.8885],
        [0.5336, 0.1774, 0.1638],
        [0.6259, 0.5376, 0.0760]])
第一种加法结果
tensor([[0.7014, 0.0009, 0.6775],
        [0.0304, 0.0759, 0.1562],
        [0.3829, 0.5190, 0.8885],
        [0.5336, 0.1774, 0.1638],
        [0.6259, 0.5376, 0.0760]])
第二种加法结果
tensor([[0.7659, 0.3630, 0.7677],
        [0.0308, 0.1960, 0.8200],
        [1.3477, 0.7604, 0.9311],
        [1.2765, 0.7849, 0.6634],
        [0.7062, 0.7491, 0.3598]])


In [8]:
print(x)
x[:,1]

tensor([[6.4485e-02, 3.6213e-01, 9.0230e-02],
        [4.0126e-04, 1.2015e-01, 6.6389e-01],
        [9.6473e-01, 2.4135e-01, 4.2606e-02],
        [7.4289e-01, 6.0757e-01, 4.9955e-01],
        [8.0281e-02, 2.1153e-01, 2.8384e-01]])


tensor([0.3621, 0.1202, 0.2414, 0.6076, 0.2115])

In [9]:
a = t.ones(5)
b = a.numpy()   #Tensor ==> numpy
a, b

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [10]:
a = np.ones(5)
b = t.from_numpy(a)
a, b

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [11]:
b.add_(1)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [12]:
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
z

tensor([[0.8304, 0.7252, 0.8579],
        [0.0312, 0.3162, 1.4839],
        [2.3124, 1.0018, 0.9737],
        [2.0194, 1.3925, 1.1629],
        [0.7865, 0.9607, 0.6436]], device='cuda:0')

In [13]:
#用list的数据创建
a = t.Tensor([[1, 2, 3],[4, 5, 6]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
#把tensor转为list
a.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [18]:
#返回元素个数,等价a.nelement()
a.numel()

6

In [20]:
a.size()

torch.Size([2, 3])

In [44]:
#形状对比
b = t.Tensor(a.size())
c = t.Tensor([2, 3])
d = t.Tensor(t.Size([2, 3]))
print(b)
print(c)
print(d)

tensor([[1.5469e+03, 4.5724e-41, 1.5469e+03, 4.5724e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5469e+03]])
tensor([2., 3.])
tensor([[1.5469e+03, 4.5724e-41, 1.5469e+03],
        [4.5724e-41, 4.4842e-44, 0.0000e+00]])


In [45]:
a = t.ones(3, 5)
b = t.zeros(2, 4)
c = t.linspace(1, 10 ,2)
d = t.arange(1, 10, 2)
e = t.randn(3, 3)
f = t.eye(3, 3)
g = t.eye(3, 4)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([ 1., 10.])
tensor([1, 3, 5, 7, 9])
tensor([[ 0.7548,  0.2191, -0.2791],
        [-1.7773,  1.2422, -0.3086],
        [ 1.6460,  0.3187, -0.4255]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


In [111]:
#tensor.view可以调整tensor的形状
a = t.arange(0, 6)
print(a)
print(a.view(2, 3).size())   #等价与reshape()、resize()

b = a.view(-1, 3)
print(b)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [113]:
#unsqueeze
print(b)
print(b.size())
print(b.unsqueeze(1).size())

tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])
torch.Size([2, 1, 3])


In [114]:
#squeeze,压缩所有1维
c = b.view(2, 1, 1, 1, 3)
print(c)
print(c.squeeze(1).size())
print(c.squeeze().size())

tensor([[[[[0, 1, 2]]]],



        [[[[3, 4, 5]]]]])
torch.Size([2, 1, 1, 3])
torch.Size([2, 3])


In [151]:
re = t.arange(0,12)
re = re.view(3,4)
re[1] = 10
re.resize_(4,4)   #自动分配空间
re

tensor([[ 0,  1,  2,  3],
        [10, 10, 10, 10],
        [ 8,  9, 10, 11],
        [ 0,  0,  0, 65]])

#### 索引

In [169]:
a = t.randn(3, 4)
print(a)
print(a[0])    #第0行
print(a[:, 0])    #第0列
print(a[(0,2)])  #等价于   a[0][2] 
print(a[:2])    #前两行
print(a[:2, 2:])     #前两行后两列
print(a>1)     #返回真假

tensor([[ 1.7043,  0.5834, -0.1240, -0.0676],
        [ 0.5247,  1.8704,  1.2117, -0.3787],
        [ 0.4269,  0.3531,  0.8769,  0.8907]])
tensor([ 1.7043,  0.5834, -0.1240, -0.0676])
tensor([1.7043, 0.5247, 0.4269])
tensor(-0.1240)
tensor([[ 1.7043,  0.5834, -0.1240, -0.0676],
        [ 0.5247,  1.8704,  1.2117, -0.3787]])
tensor([[-0.1240, -0.0676],
        [ 1.2117, -0.3787]])
tensor([[1, 0, 0, 0],
        [0, 1, 1, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
