In [1]:
from __future__ import print_function
import torch as t
import numpy as np
#指定形状
x = t.Tensor(5, 3)
x

tensor([[-1.2557e-02,  4.5866e-41, -1.2557e-02],
        [ 4.5866e-41, -1.6606e-02,  4.5866e-41],
        [ 3.9970e+00,  4.5866e-41, -1.7964e-07],
        [ 4.5866e-41,  5.5388e-14,  2.5614e+21],
        [ 7.7146e+31,  1.8057e+28,  7.7574e-40]])

In [2]:
#使用[0,1]均匀分布随机初始化二维数组
x = t.rand(5, 3)
y = t.rand(5, 3)
x

tensor([[0.6886, 0.4735, 0.9999],
        [0.7025, 0.3589, 0.2468],
        [0.3373, 0.9022, 0.3055],
        [0.7220, 0.9194, 0.0708],
        [0.6658, 0.0482, 0.3572]])

In [3]:
#查看x形状
print(x.size())

#查看列个数,方法1
#方法1
x.size()[0]

#方法2
x.size(0)


torch.Size([5, 3])


5

In [4]:
x + y         #1
t.add(x, y)   #2
result = t.Tensor(5, 3)    #3 
t.add(x, y, out=result)
result

tensor([[0.9124, 0.9196, 1.8272],
        [1.6191, 0.4689, 0.3455],
        [1.1317, 0.9565, 1.2894],
        [1.4088, 1.6295, 1.0270],
        [1.4604, 0.9562, 0.9437]])

In [5]:
print ('最初的y')
print (y)

print('第一种加法结果')
y.add(x)  #普通加法，不改变y的值
print (y)

print('第二种加法结果')
y.add_(x)  #inplace 加法，改变y的值
print (y)

最初的y
tensor([[0.2238, 0.4461, 0.8273],
        [0.9166, 0.1100, 0.0987],
        [0.7945, 0.0542, 0.9839],
        [0.6868, 0.7101, 0.9562],
        [0.7946, 0.9080, 0.5865]])
第一种加法结果
tensor([[0.2238, 0.4461, 0.8273],
        [0.9166, 0.1100, 0.0987],
        [0.7945, 0.0542, 0.9839],
        [0.6868, 0.7101, 0.9562],
        [0.7946, 0.9080, 0.5865]])
第二种加法结果
tensor([[0.9124, 0.9196, 1.8272],
        [1.6191, 0.4689, 0.3455],
        [1.1317, 0.9565, 1.2894],
        [1.4088, 1.6295, 1.0270],
        [1.4604, 0.9562, 0.9437]])


In [6]:
print(x)
x[:,1]

tensor([[0.6886, 0.4735, 0.9999],
        [0.7025, 0.3589, 0.2468],
        [0.3373, 0.9022, 0.3055],
        [0.7220, 0.9194, 0.0708],
        [0.6658, 0.0482, 0.3572]])


tensor([0.4735, 0.3589, 0.9022, 0.9194, 0.0482])

In [7]:
a = t.ones(5)
b = a.numpy()   #Tensor ==> numpy
a, b

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [8]:
a = np.ones(5)
b = t.from_numpy(a)
a, b

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [9]:
b.add_(1)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [10]:
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
z

tensor([[1.6010, 1.3931, 2.8271],
        [2.3216, 0.8278, 0.5924],
        [1.4690, 1.8587, 1.5950],
        [2.1308, 2.5488, 1.0978],
        [2.1262, 1.0045, 1.3009]], device='cuda:0')

In [11]:
#用list的数据创建
a = t.Tensor([[1, 2, 3],[4, 5, 6]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
#把tensor转为list
a.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [13]:
#返回元素个数,等价a.nelement()
a.numel()

6

In [14]:
a.size()

torch.Size([2, 3])

In [15]:
#形状对比
b = t.Tensor(a.size())
c = t.Tensor([2, 3])
d = t.Tensor(t.Size([2, 3]))
print(b)
print(c)
print(d)

tensor([[-1.2557e-02,  4.5866e-41,  4.1709e-35],
        [ 3.0620e-41,  4.4842e-44,  0.0000e+00]])
tensor([2., 3.])
tensor([[-1.2557e-02,  4.5866e-41, -6.5966e+07],
        [ 3.0618e-41,  4.4842e-44,  0.0000e+00]])


In [16]:
a = t.ones(3, 5)
b = t.zeros(2, 4)
c = t.linspace(1, 10 ,2)
d = t.arange(1, 10, 2)
e = t.randn(3, 3)
f = t.eye(3, 3)
g = t.eye(3, 4)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([ 1., 10.])
tensor([1, 3, 5, 7, 9])
tensor([[-0.4039, -0.6068,  0.0085],
        [-0.3548,  0.8186,  1.5256],
        [-0.6916, -0.9132, -0.9615]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


In [17]:
#tensor.view可以调整tensor的形状
a = t.arange(0, 6)
print(a)
print(a.view(2, 3).size())   #等价与reshape()、resize()

b = a.view(-1, 3)
print(b)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [18]:
#unsqueeze
print(b)
print(b.size())
print(b.unsqueeze(1).size())

tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])
torch.Size([2, 1, 3])


In [19]:
#squeeze,压缩所有1维
c = b.view(2, 1, 1, 1, 3)
print(c)
print(c.squeeze(1).size())
print(c.squeeze().size())

tensor([[[[[0, 1, 2]]]],



        [[[[3, 4, 5]]]]])
torch.Size([2, 1, 1, 3])
torch.Size([2, 3])


In [20]:
re = t.arange(0, 12)
re = re.view(3, 4)
re[1] = 10
re.resize_(4, 4)   #自动分配空间
re

tensor([[             0,              1,              2,              3],
        [            10,             10,             10,             10],
        [             8,              9,             10,             11],
        [93848498348360, 93848498348360, 93848498348400,              1]])

## 索引

In [22]:
a = t.randn(3, 4)
print(a)
print(a[0])    #第0行
print(a[:, 0])    #第0列
print(a[(0, 2)])  #等价于   a[0][2] 
print(a[:2])    #前两行
print(a[:2, 2:])     #前两行后两列
print(a>1)     #返回真假

tensor([[ 0.0625, -2.7976, -0.1221, -1.7186],
        [ 0.8997,  0.5776,  0.0117,  0.7595],
        [ 0.2842, -0.3333, -1.3502,  0.8680]])
tensor([ 0.0625, -2.7976, -0.1221, -1.7186])
tensor([0.0625, 0.8997, 0.2842])
tensor(-0.1221)
tensor([[ 0.0625, -2.7976, -0.1221, -1.7186],
        [ 0.8997,  0.5776,  0.0117,  0.7595]])
tensor([[-0.1221, -1.7186],
        [ 0.0117,  0.7595]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)


In [23]:
a = t.linspace(0, 11, 12)
a1 = a.view(3, 4)
indices = t.LongTensor([0, 1, 3])
b = t.index_select(a, 0, indices)
b1 = t.index_select(a1, 1, indices)
a, b, a1, b1

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([0., 1., 3.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  3.],
         [ 4.,  5.,  7.],
         [ 8.,  9., 11.]]))

In [24]:
a = t.linspace(0, 11, 12)
b = a.view(3, 4)
c = t.masked_select(a, a>6)
d = t.masked_select(b, b>6)
a, b, c, d

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 7.,  8.,  9., 10., 11.]),
 tensor([ 7.,  8.,  9., 10., 11.]))

In [25]:
a = t.randn(3, 4)
b = a>1
print(b)
c = t.nonzero(b)
print(c)

tensor([[0, 0, 0, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]], dtype=torch.uint8)
tensor([[1, 1],
        [1, 3],
        [2, 0],
        [2, 2]])


In [26]:
a = t.arange(0, 16).view(4, 4)
index = t.LongTensor([[0, 1, 2, 3],[1, 1, 1, 1]])
b = t.gather(a, 0, index)
c = t.gather(a, 1, index.t())
9print(a)
print(b)
print(c)

SyntaxError: invalid syntax (<ipython-input-26-abd33d05258a>, line 5)

In [27]:
a = t.arange(0,27).view(3,3,3)
print(a)
print(a[[1, 1, 2],[2, 2, 0]])
print(a[[1, 2], [1, 2], [2, 0]])

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[15, 16, 17],
        [15, 16, 17],
        [18, 19, 20]])
tensor([14, 24])


## 常见的逐元素操作
#### abs/sqrt/div/exp/fmod/log/pow                  绝对值/平方根/除法/指数/求余/求幂
#### cos/sin/asin/atan2/cosh                                  三角函数
#### ceil/round/floor/trunc                                      上取整/四舍五入/下取整/只保留/整数部分
#### clamp(input,min,max)                                   超过min和max部分截断
#### sigmoid/tanh                                                    激活函数

## 常见的归并操作
#### mean/sum/median/mode  均值/和/中位数/众数
#### norm/dist 范数/距离
#### std/var 标准差/方差
#### cumsum/cumprod 累加/累乘

In [28]:
# abs/sqrt/div/exp/fmod/log/pow                      
# 绝对值/平方根/除法/指数/求余/求对数/求幂
a = t.randn(6).view(2,3)
b = t.abs(a)
c = t.sqrt(b)
d = t.div(c, 2)
e = t.exp(c)
f = t.arange(6)
f = t.fmod(f, 4)
g = t.log(e)
h = t.pow(f, 2)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

tensor([[ 0.9662, -0.1790,  0.9489],
        [ 0.5241,  0.5033,  0.1949]])
tensor([[0.9662, 0.1790, 0.9489],
        [0.5241, 0.5033, 0.1949]])
tensor([[0.9830, 0.4231, 0.9741],
        [0.7240, 0.7094, 0.4415]])
tensor([[0.4915, 0.2115, 0.4871],
        [0.3620, 0.3547, 0.2207]])
tensor([[2.6724, 1.5266, 2.6489],
        [2.0626, 2.0328, 1.5550]])
tensor([0, 1, 2, 3, 0, 1])
tensor([[0.9830, 0.4231, 0.9741],
        [0.7240, 0.7094, 0.4415]])
tensor([0, 1, 4, 9, 0, 1])


In [29]:
# cos/sin/asin/atan2/cosh                                 
# 三角函数
a = t.randn(2,3)
b = t.cos(a)
c = t.sin(a)
d = t.asin(a)
e = t.atan(a)


print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[ 0.1978, -0.5336, -1.9978],
        [ 0.7277,  2.1877, -0.0506]])
tensor([[ 0.9805,  0.8610, -0.4142],
        [ 0.7467, -0.5785,  0.9987]])
tensor([[ 0.1965, -0.5086, -0.9102],
        [ 0.6652,  0.8156, -0.0506]])
tensor([[ 0.1991, -0.5629,     nan],
        [ 0.8150,     nan, -0.0506]])
tensor([[ 0.1952, -0.4902, -1.1067],
        [ 0.6291,  1.1421, -0.0506]])


In [36]:
#Tensor与Numpy

import numpy as np
a = np.ones([2, 3], dtype=np.float32)
b = t.from_numpy(a)
c = t.Tensor(a)
d = b.numpy()
print(a)
print(b)
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]]
