In [4]:
import torch as t
from torch.autograd import Variable

In [6]:
x = Variable(t.ones(2,2),requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [8]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [11]:
y.grad_fn

In [13]:
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [14]:
y.backward()
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [15]:
y.backward()
x.grad

tensor([[4., 4.],
        [4., 4.]])

In [16]:
x.grad.data.zero_()
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [28]:
#Variable和Tensor接口近乎一致，可以做到无缝切换
x = Variable(t.ones(4,5))
y = t.cos(x)
x_tensor_cos = t.cos(x.data)
x, y, x.data, x_tensor_cos



(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
         [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
         [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
         [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
         [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
         [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
         [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]]))